# Shared costmap parameters for Summit XL
obstacle_range: 8.0
raytrace_range: 10.0
footprint: [[0.45, -0.40], [0.45, 0.40], [-0.45, 0.40], [-0.45, -0.40]]
inflation_radius: 0.55
cost_scaling_factor: 5.0

observation_sources: laser_scan_sensor

laser_scan_sensor:
  sensor_frame: laser_link
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
  min_obstacle_height: 0.0
  max_obstacle_height: 2.0
  obstacle_range: 8.0
  raytrace_range: 10.0
